name: sunshine
description: Sun Shine Weather
publish_to: 'none'

version: 1.2.2+8

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.3
  rxdart: ^0.27.3
  logger: ^2.0.2+1
  lottie: ^2.7.0
  go_router: ^12.1.1
  url_strategy: ^0.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.9
  location: ^5.0.3
  geolocator: ^10.1.0
  permission_handler: ^11.2.0


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.2
  build_runner: ^2.1.2
  mockito: ^5.0.15
  mocktail: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  json_serializable: ^6.7.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/weather_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/weather_logo.png
    - assets/sunshine.png
    - assets/logo/
    - assets/icon/

 
 
 
 

 
 

 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
